### ISSUE TITLE
Sending a retained message with empty payload obliterates RetainedTree

### ISSUE THREAD

**Issue by raichoo** [lpeterse/haskell-mqtt#11]
Hi,

I've had some issues with retained retained messages that have an empty payload. Rather than just deleting that specific topic such a message seems to obliterate the entire `RetainedTree`.

Looks like the order of the arguments of the `difference` function is flipped `Network.MQTT.Broker.RetainedMessages` are flipped. I've hot fixed this issue simply by changing the code to:

```haskell

delete :: Message.Message -> RetainedTree -> RetainedTree
delete msg = flip difference (singleton msg)

```

I'm not quite sure if this fixes an actual problem or if I'm just misunderstanding things here. So this is pretty much a "request for comments" :)

Kind regards,
raichoo

**Comment by sclausen** [comment]
We totally missed that behavior. Many thanks @raichoo!

**Comment by raichoo** [comment]
Glad I could help, thanks for the library :)
